In [13]:
import rosbag
from sensor_msgs import point_cloud2
from sensor_msgs.msg import PointCloud
import numpy as np

bag_path = '/home/shitong/Datasets/kitti_2011_09_30_drive_0016_synced.bag'

bag_data = rosbag.Bag(bag_path)
info = bag_data.get_type_and_topic_info()
# print(info)

velodyne_data = bag_data.read_messages('/kitti/velo/pointcloud')
# cur_pc = point_cloud2.read_points_list(velodyne_data)
# cur_pc_data = np.array(cur_pc.data)

for topic, msg, t in velodyne_data:
    cur_pc = point_cloud2.read_points(msg)
    cur_pc_data = np.array(list(cur_pc))
    print(cur_pc_data)
    break

[[ 5.94760017e+01  1.47069998e+01  2.28099990e+00  0.00000000e+00]
 [ 5.94449997e+01  1.48979998e+01  2.28099990e+00  0.00000000e+00]
 [ 5.93639984e+01  1.51750002e+01  2.28099990e+00  0.00000000e+00]
 ...
 [ 3.75300002e+00 -1.42600000e+00 -1.75600004e+00  2.89999992e-01]
 [ 3.77200007e+00 -1.41999996e+00 -1.76400006e+00  2.89999992e-01]
 [ 3.76799989e+00 -1.40499997e+00 -1.75899994e+00  5.00000007e-02]]
